### ISSUE TITLE
Puesta en marcha del equipo

### ISSUE THREAD

**Issue by GabrielTechs** [GabrielTechs/BeeControl#1]
Link de template: https://docs.google.com/document/d/1HyWIaRhtWIXU-I_CM5VBFd-Zs9IXlC5-kxeBF7xZHT4/edit#bookmark=id.gjdgxs

- [x] Programa asignatura
- [x] Perfil corporativo del equipo
- [x] Gestión del equipo de proyecto
- [x] Gestión del proyecto
- [x] Anexos

**Comment by JMarinez** [comment]
Revisar que falta en los Anexos @GabrielTechs

**Comment by JMarinez** [comment]
Cambiar el 4.6?? @GabrielTechs
