### ISSUE TITLE
Informe de entrevista

### ISSUE THREAD

**Issue by GabrielTechs** [GabrielTechs/BeeControl#4]
Link del template a utilizar:
https://docs.google.com/document/d/13YuM8g4S2DPAOGaPfhlwJ13PMgL3EjLhC3G4_qrmiPg/edit?usp=sharing

- [x] Propósito
- [x] Objetivo
- [x] Descripción del proceso
- [x] Entregables del proceso
- [x] Resumen
- [x] Anexos

**Comment by JMarinez** [comment]
@GabrielTechs revisar Punto 3 por si esta bien planteado
